
[window]
dynamic_padding = true
option_as_alt = "Both"
opacity = 0.95
blur = true
startup_mode = "Maximized"

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
bold = { style = "SemiBold" }
bold_italic = { style = "SemiBold Italic" }
size = 13

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Underline"

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" },
  { key = "T", mods = "Command", action = "None" },
]

[general]

live_config_reload = true
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

# [shell]
# program = "/opt/homebrew/bin/fish"
# args = ["-c", "tmux new-session -A -s alacritty"]
