import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

live_config_reload = true

[font]
normal.family = "SauceCodePro Nerd Font"
size = 13

[window]
dynamic_padding = true
option_as_alt = "Both"
opacity = 0.95
blur = true
startup_mode = "Maximized"

[cursor]
style.shape = "Underline"

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" },
  { key = "T", mods = "Command", action = "None" },
]

# [shell]
# program = "/opt/homebrew/bin/fish"
# args = ["-c", "tmux new-session -A -s alacritty"]
