include           ./themes/mocha.conf

# Font
font_family       family="SauceCodePro Nerd Font"
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         13.0

# Cursor
cursor_shape      underline

# Background
background_opacity  0.9
background_blur     50

# Shell
# shell /opt/homebrew/bin/fish --login --interactive -c "tmux new-session -A -s kitty"
shell_integration     no-cursor

# MacOS
macos_option_as_alt both

# Key Mappings
map kitty_mod+enter   no_op
map kitty_mod+t       no_op
map kitty_mod+n       no_op

