# Font settings
font_family      JetBrainsMono Nerd Font
font_size 13.0

# Cursor settings
cursor_shape underline

# MacOS option key mapping
macos_option_as_alt yes

# Cursor settings
# tab_bar_edge top
# tab_bar_style powerline
# tab_bar_min_tabs 1
# active_tab_font_style   bold-italic
# active_tab_foreground #212337
# active_tab_background #89ca78
# inactive_tab_font_style normal
# inactive_tab_foreground   #89ca78
# inactive_tab_background   #212337
# tab_bar_background #0e0e0e

