# Set default shell to fish
set-option -g default-shell $SHELL

# Status position
set-option -g status-position top

# Default terminal overrides
set-option -sa terminal-overrides ',alacritty:RGB'
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[3 q'

# Change the prefix key to M-b
set -g prefix M-b
unbind C-b
bind M-b send-prefix

# Turn on mouse
set-option -g mouse on

# TMUX:refresh (seconds)
set-option -g status-interval 2

# Theme
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'

# Theme:extras
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'

# Theme:customization
set -g @catppuccin_status_background "default"

set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "session cpu battery host date_time"
set -g @catppuccin_status_left_separator  ""

set -g @catppuccin_directory_text "#{pane_current_path}"

# TMUX plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# TMUX plugin manager: init
run '/opt/homebrew/opt/tpm/share/tpm/tpm'
